#!/usr/bin/env bash
ScriptPath="$(readlink -f $0)"
ScriptDir="${ScriptPath%/*}"
CAPrefix="${CAName:-mjbrowns}"
CADir="${CADir:-${PWD}/CA}"
CACRT="${CADir}/${CAPrefix}-ca.crt"
CAKEY="${CADir}/${CAPrefix}-ca.key"
CAEXT="${CADir}/${CAPrefix}.ext"
CSRCONF="${CADir}/${CAPrefix}-csr.conf"

function die {
    >&2 echo "$@"
    exit 1
}

[ -d "$CADir" ] || die "Error: CA Directory Not found!"
[ -f "$CACRT" ] || die "Error: CA Certificate Not Found!"
[ -f "$CAKEY" ] || die "Error: CA Private Key Not Found!"

function signCSRext {
    echo "Enter CSR file name:"
    read -ep "$PWD/" FN
    if [ ! -r "$FN" ] ;then
        >&2 echo "Error: CSR file not found or not readable"
        return
    fi
    FNO="${FN%.*}.crt"
    FNE="${FN%.*}"
    FNE="${FNE##*/}"

    echo "Processing CSR $FN, output is $FNO"
    openssl x509 -req -in "$FN" -CA "$CACRT" -CAkey "$CAKEY" -CAcreateserial -extfile "$CAEXT" -extensions "$FNE" -out "$FNO" -days 3650
}
function signCSR {
    echo "Enter CSR filename: " 
    read -ep "$PWD/" FN
    if [ ! -r "$FN" ] ;then
        >&2 echo "Error: CSR file not found or not readable"
        return
    fi
    FNO="${FN%.*}.crt"

    echo "Processing CSR $FN, output is $FNO"
    openssl x509 -req -in "$FN" -CA "$CACRT" -CAkey "$CAKEY" -CAcreateserial -out "$FNO" -days 3650
}

showCert() {
    echo "Enter Cert Filename:"
    read -ep "$PWD/" FN
    if [ ! -r "$FN" ]; then
        >&2 echo "Error: file not found or not readable"
        return
    fi
    case ${FN##*.} in
        csr)
            openssl req -in "$FN" -text -noout -reqopt no_pubkey,no_sigdump
            ;;
        crt)
            openssl x509 -in "$FN" -text -noout -certopt no_pubkey,no_sigdump
            ;;
    esac
}

genCSR() {
    echo "Enter CSR Filename:"
    read -ep "$PWD/" FN
    FCSR="${FN%.*}.csr"
    FKEY="${FN%.*}.key"
    echo "Using $FCSR and $FKEY"
    touch "$FCSR" || {
        >&2 echo "Error: file could not be opened for writing"
        return
    }
    openssl req -newkey rsa:2048 -keyout "$FKEY" -out "$FCSR" -nodes -config "$CSRCONF"
}

makeBundle() {
    echo "Enter Private Key Filename:"
    read -ep "$PWD/" FKEY 
    [ -r "$FKEY" ] || {
        >&2 echo "Error: file not found or not readable"
        return
    }
    echo "Enter Certificate Filename:"
    read -ep "$PWD/" FCRT
    [ -r "$FKEY" ] || {
        >&2 echo "Error: file not found or not readable"
        return
    }
    FN="${FCRT%.*}-bundle.pem"
    echo "Writing $FN"
    cat "$FKEY" "$FCRT" "$CACRT" > "$FN"
}

function showHelp {
    echo "Functions"
    echo ""
    echo "c - generate a certificate request (CSR)"
    echo "s - sign a certificate request"
    echo "e - sign a certificate request with extensions"
    echo "v - view a certificate or request"
    echo "b - create a PEM bundle (key, crt, CA)"
    echo "d - edit the extensions database"
    echo ""
    echo "q - quit"
    echo ""
}

function menu {
    showHelp
    typeset -l mchoice=""
    read -p "Choice? " mchoice
    case "$mchoice" in 
        c)  genCSR ;;
        s)  signCSR ;;
        e)  signCSRext ;;
        v)  showCert ;;
        b)  makeBundle ;;
        d)  vi "$CAEXT" ;;
        q)  mexit="y" ;;
    esac
}

typeset -l mexit="n"
while [ "$mexit" != "y" ]; do
    menu
done 
